name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executables with PyInstaller
        shell: pwsh
        run: |
          pyinstaller gui.py --name LSM-GUI --noconsole --onefile --clean --add-data "config.yaml;." --collect-all PySide6 --hidden-import serial --hidden-import serial.tools.list_ports
          pyinstaller run.py --name LSM-Reader --onefile --clean --add-data "config.yaml;." --collect-all PySide6 --hidden-import serial --hidden-import serial.tools.list_ports

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress -y

      - name: Build installer with Inno Setup
        run: |
          "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" installer\lsm_setup.iss

      - name: Upload artifacts (EXEs and Installer)
        uses: actions/upload-artifact@v4
        with:
          name: LSM-Windows-Build
          path: |
            dist/LSM-GUI.exe
            dist/LSM-Reader.exe
            installer/Output/LSM-Setup.exe

      - name: Create GitHub Release and upload binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installer/Output/LSM-Setup.exe
            dist/LSM-GUI.exe
            dist/LSM-Reader.exe
